services:
  sireco-back:
    build:
      context: "./Sireco Back"
      dockerfile: './dockerfile'
    ports:
      - '3000:3000'
    links:
      - db
  sireco-front:
    build:
      context: "./Sireco Front"
      dockerfile: './dockerfile'
    ports:
      - '5500:5500'
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'sirecodb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'remote'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1235'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:



  # services:
  # service-name:
  #   build:
  #     context: ../app
  #     dockerfile: ../docker/Dockerfile