services:
  backend:
    build:
      context: ./sireco_back
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_USER=remote
      - DB_PASSWORD=6Efj3m7jO0GAtd8k
      - DB_NAME=sirecodb
      - DB_ROOT_PASSWORD=Marchiquit4
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./sireco_front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Marchiquit4
      MYSQL_DATABASE: sirecodb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Marchiquit4
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: