version: '3.8'
services:
  sireco-back:
    build:
      context: "./Sireco Back"
      dockerfile: './dockerfile'
    ports:
      - '3000:3000'

  sireco-front:
    build:
      context: "./Sireco Front"
      dockerfile: './dockerfile'
    ports:
      - '80:80'

  db:
    image: mysql
    restart: always
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - mydb-sireco:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'sirecodb'
      MYSQL_USER: 'remote'
      MYSQL_PASSWORD: '1235'
      MYSQL_ROOT_PASSWORD: 'Mar.chiquit4!'
    ports:
      - '3306:3306'
    expose:
      - '3306'
volumes:
  mydb-sireco:
