CREATE TABLE `CONTRIBUYENTES` (
	`NRO_CONTRIB` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`CUIL` VARCHAR(13),
	`NOMBRE` VARCHAR(30),
	`APELLIDO` VARCHAR(30),
	`DIRECCION` VARCHAR(255),
	`EMAIL` VARCHAR(30),
	`TELEFONO` INTEGER,
	`PROVINCIA` VARCHAR(45),
	`LOCALIDAD` VARCHAR(45),
	`CP` INTEGER CHECK(8),
	`FECHA` TIMESTAMP,
	PRIMARY KEY(`NRO_CONTRIB`)
);


CREATE TABLE `INMUEBLES` (
	`NRO_INM` INTEGER NOT NULL UNIQUE,
	`NRO_CONT` INTEGER,
	`RECURSO` VARCHAR(15) COMMENT 'ABL ó Red Vial',
	PRIMARY KEY(`NRO_INM`)
);


CREATE TABLE `RODADOS` (
	`NRO_ROD` INTEGER NOT NULL UNIQUE,
	`NRO_CONT` INTEGER,
	`RECURSO` VARCHAR(10) COMMENT 'Moto o Vehiculo',
	`PATENTE` VARCHAR(12) UNIQUE,
	PRIMARY KEY(`NRO_ROD`)
);


CREATE TABLE `COMERCIOS` (
	`NRO_COM` INTEGER NOT NULL UNIQUE,
	`NRO_CONT` INTEGER,
	PRIMARY KEY(`NRO_COM`)
);


CREATE TABLE `CEMENTERIO` (
	`NRO_CUENTA` INTEGER NOT NULL UNIQUE,
	`NRO_CONT` INTEGER,
	PRIMARY KEY(`NRO_CUENTA`)
);


ALTER TABLE `INMUEBLES`
ADD FOREIGN KEY(`NRO_CONT`) REFERENCES `CONTRIBUYENTES`(`NRO_CONTRIB`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `COMERCIOS`
ADD FOREIGN KEY(`NRO_CONT`) REFERENCES `CONTRIBUYENTES`(`NRO_CONTRIB`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `RODADOS`
ADD FOREIGN KEY(`NRO_CONT`) REFERENCES `CONTRIBUYENTES`(`NRO_CONTRIB`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CEMENTERIO`
ADD FOREIGN KEY(`NRO_CONT`) REFERENCES `CONTRIBUYENTES`(`NRO_CONTRIB`)
ON UPDATE NO ACTION ON DELETE NO ACTION;