// Mapeo de municipios por provincia
const municipiosPorProvincia = {
    "BUENOS AIRES": [
      "HURLINGHAM",
      "COLON",
      "BENITO JUAREZ",
      "OLAVARRIA",
      "ALMIRANTE BROWN",
      "JOSE C PAZ",
      "ROJAS",
      "GENERAL BELGRANO",
      "SUIPACHA",
      "LOBERIA",
      "GENERAL VILLEGAS",
      "ESTEBAN ECHEVERRIA",
      "MONTE",
      "BALCARCE",
      "PRESIDENTE PERON",
      "CARMEN DE ARECO",
      "GUAMINI",
      "CHACABUCO",
      "GENERAL PUEYRREDON",
      "PILAR",
      "GENERAL PINTO",
      "VICENTE LOPEZ",
      "GENERAL JUAN MADARIAGA",
      "SALADILLO",
      "VILLARINO",
      "SAN PEDRO",
      "GENERAL GUIDO",
      "SAN ISIDRO",
      "TIGRE",
      "CASTELLI",
      "SAN CAYETANO",
      "PINAMAR",
      "TRENQUE LAUQUEN",
      "CORONEL DORREGO",
      "ENSENADA",
      "ALBERTI",
      "LOMAS DE ZAMORA",
      "CAMPANA",
      "GENERAL ALVARADO",
      "EZEIZA",
      "SAN MIGUEL",
      "ADOLFO ALSINA",
      "SAAVEDRA",
      "ADOLFO GONZALES CHAVES",
      "TRES DE FEBRERO",
      "SAN ANDRES DE GILES",
      "SALLIQUELO",
      "BRANDSEN",
      "MONTE HERMOSO",
      "TRES LOMAS",
      "MERLO",
      "QUILMES",
      "JUNIN",
      "BERAZATEGUI",
      "BRAGADO",
      "MAGDALENA",
      "HIPOLITO YRIGOYEN",
      "PATAGONES",
      "LANÚS",
      "CHASCOMUS",
      "MERCEDES",
      "RIVADAVIA",
      "CORONEL PRINGLES",
      "CAPITAN SARMIENTO",
      "GENERAL SAN MARTIN",
      "RAMALLO",
      "PILA",
      "LAS FLORES",
      "NECOCHEA",
      "GENERAL RODRIGUEZ",
      "AZUL",
      "CAÑUELAS",
      "CARLOS CASARES",
      "SAN NICOLAS",
      "MAIPU",
      "MALVINAS ARGENTINAS",
      "PEHUAJO",
      "SAN VICENTE",
      "PERGAMINO",
      "MORENO",
      "CORONEL DE MARINA L ROSALES",
      "LINCOLN",
      "FLORENTINO AMEGHINO",
      "LEZAMA",
      "MORON",
      "ESCOBAR",
      "BERISSO",
      "BOLIVAR",
      "EXALTACION DE LA CRUZ",
      "GENERAL ALVEAR",
      "TORNQUIST",
      "ZARATE",
      "LEANDRO N ALEM",
      "LUJAN",
      "LA COSTA",
      "GENERAL PAZ",
      "RAUCH",
      "CHIVILCOY",
      "SAN FERNANDO",
      "BARADERO",
      "MARCOS PAZ",
      "ITUZAINGO",
      "LOBOS",
      "9 DE JULIO",
      "BAHIA BLANCA",
      "GENERAL LAVALLE",
      "DAIREAUX",
      "CARLOS TEJEDOR",
      "LA MATANZA",
      "25 DE MAYO",
      "AVELLANEDA",
      "ARRECIFES",
      "LAPRIDA",
      "TAPALQUE",
      "PUAN",
      "PELLEGRINI",
      "DOLORES",
      "GENERAL ARENALES",
      "GENERAL LAS HERAS",
      "GENERAL VIAMONTE",
      "SAN ANTONIO DE ARECO",
      "SALTO",
      "NAVARRO",
      "LA PLATA",
      "PUNTA INDIO",
      "TRES ARROYOS",
      "GENERAL LA MADRID",
      "CORONEL SUAREZ",
      "VILLA GESELL",
      "TANDIL",
      "FLORENCIO VARELA",
      "MAR CHIQUITA",
      "AYACUCHO",
      "TORDILLO",
      "ROQUE PEREZ",
    ],
    "CATAMARCA": [
      "FRAY MAMERTO ESQUIU",
      "VILLA VIL",
      "LAS JUNTAS",
      "EL RODEO",
      "SANTA MARIA",
      "ICAÑO",
      "POMAN",
      "EL ALTO",
      "ACONQUIJA",
      "HUILLAPIMA",
      "VALLE VIEJO",
      "BELEN",
      "ANCASTI",
      "CAPAYAN",
      "PACLIN",
      "SAN FERNANDO",
      "PUERTA DE CORRAL QUEMADO",
      "RECREO",
      "SANTA ROSA",
      "TINOGASTA",
      "LOS ALTOS",
      "ANDALGALA",
      "SAN FERNANDO DEL VALLE DE CATAMARCA",
      "LONDRES",
      "LA PUERTA",
      "POZO DE PIEDRA",
      "CORRAL QUEMADO",
      "SAN JOSE",
      "LOS VARELA",
      "ANTOFAGASTA DE LA SIERRA",
      "MUTQUIN",
      "SAUJIL",
      "PUERTA DE SAN JOSE",
      "HUALFIN",
      "TAPSO",
      "FIAMBALA",
    ],
    "CHACO": [
      "LA ESCONDIDA",
      "GANCEDO",
      "CORZUELA",
      "ENRIQUE URIEN",
      "MIRAFLORES",
      "EL ESPINILLO",
      "MISION NUEVA POMPEYA",
      "LAPACHITO",
      "COLONIAS UNIDAS",
      "COLONIA ABORIGEN",
      "PUERTO EVA PERON",
      "CORONEL DU GRATY",
      "LA EDUVIGIS",
      "BARRANQUERAS",
      "LAGUNA BLANCA",
      "LA CLOTILDE",
      "VILLA ANGELA",
      "PRESIDENCIA DE LA PLAZA",
      "VILLA BERTHET",
      "MARGARITA BELEN",
      "LA LEONESA",
      "COLONIA BENITEZ",
      "LAGUNA LIMPIA",
      "MAKALLE",
      "NAPENAY",
      "HERMOSO CAMPO",
      "PUERTO TIROL",
      "PRESIDENCIA ROCA",
      "TRES ISLETAS",
      "GENERAL SAN MARTIN",
      "RESISTENCIA",
      "MACHAGAI",
      "BASAIL",
      "COTE LAI",
      "TACO POZO",
      "PUERTO VILELAS",
      "LOS FRENTONES",
      "GENERAL CAPDEVILA",
      "CONCEPCION DEL BERMEJO",
      "CIERVO PETISO",
      "FONTANA",
      "GENERAL PINEDO",
      "FUERTE ESPERANZA",
      "SAMUHU",
      "PRESIDENCIA ROQUE SAENZ PEÑA",
      "JUAN JOSE CASTELLI",
      "COLONIA POPULAR",
      "CHARADAI",
      "LA VERDE",
      "CAPITAN SOLARI",
      "LAS PALMAS",
      "LAS GARCITAS",
      "COLONIA ELISA",
      "AVIA TERAI",
      "PAMPA DEL INFIERNO",
      "CHARATA",
      "LAS BREÑAS",
      "SANTA SYLVINA",
      "EL SAUZALITO",
      "VILLA RIO BERMEJITO",
      "CHOROTIS",
      "ISLA DEL CERRITO",
      "GENERAL VEDIA",
      "LA TIGRA",
      "SAN BERNARDO",
      "PAMPA ALMIRON",
      "CAMPO LARGO",
      "PAMPA DEL INDIO",
      "QUITILIPI",
      "PUERTO BERMEJO",
    ],
    "CHUBUT": [
      "CARRENLEUFU",
      "LAGO BLANCO",
      "28 DE JULIO",
      "AREA SIN GOBIERNO",
      "CHOLILA",
      "ALDEA APELEG",
      "TREVELIN",
      "EPUYEN",
      "PUERTO MADRYN",
      "GUALJAINA",
      "VIGLIONE",
      "PASO DEL SAPO",
      "CUSHAMEN",
      "COMODORO RIVADAVIA",
      "GOBERNADOR COSTA",
      "RIO MAYO",
      "RAWSON",
      "CAMARONES",
      "EL MAITEN",
      "LOS ALTARES",
      "FACUNDO",
      "RADA TILLY",
      "GAIMAN",
      "EL HOYO",
      "DOLAVON",
      "TECKA",
      "TRELEW",
      "ALTO RIO SENGUER",
      "SARMIENTO",
      "LAS PLUMAS",
      "DIQUE FLORENTINO AMEGHINO",
      "RIO PICO",
      "ALDEA EPULEF",
      "COLAN CONHUE",
      "LAGO PUELO",
      "ALDEA BELEIRO",
      "PASO DE INDIOS",
      "BUEN PASTO",
      "ESQUEL",
      "GAN GAN",
      "GASTRE",
      "DOCTOR RICARDO ROJAS",
      "CERRO CENTINELA",
      "LAGUNITA SALADA",
      "CORCOVADO",
      "PUERTO PIRAMIDES",
      "JOSE DE SAN MARTIN",
      "TELSEN",
    ],
    "CIUDAD DE BUENOS AIRES": [
      "COMUNA 9",
      "COMUNA 6",
      "COMUNA 3",
      "COMUNA 7",
      "COMUNA 12",
      "COMUNA 11",
      "COMUNA 14",
      "COMUNA 10",
      "COMUNA 13",
      "COMUNA 2",
      "COMUNA 5",
      "COMUNA 15",
      "COMUNA 1",
      "COMUNA 8",
      "COMUNA 4",
    ],
    "CÓRDOBA": [
      "QUILINO",
      "ESTANCIA DE GUADALUPE",
      "LABORDE",
      "BELL VILLE",
      "AMBOY",
      "AREA SIN GOBIERNO",
      "SALSACATE",
      "LUCA",
      "LEONES",
      "COLONIA TIROLESA",
      "LOZADA",
      "SALSIPUEDES",
      "LA PUERTA",
      "LA CUMBRE",
      "SANTA ROSA DE CALAMUCHITA",
      "LOS CHAÑARITOS (RÍO SEGUNDO)",
      "LOS TALARES",
      "LA RANCHERITA",
      "VILLA HUIDOBRO",
      "MANFREDI",
      "CUESTA BLANCA",
      "DEAN FUNES",
      "VILLA DEL PRADO",
      "CAVANAGH",
      "SAN GERONIMO",
      "LAS PEÑAS",
      "SAN ESTEBAN",
      "SALDAN",
      "TICINO",
      "ISLA VERDE",
      "SINSACATE",
      "CARNERILLO",
      "CERRO COLORADO",
      "LOS ZORROS",
      "ARROYO LOS PATOS",
      "TORO PUJIO",
      "ALEJO LEDESMA",
      "MONTE MAIZ",
      "GUATIMOZIN",
      "ONAGOITY",
      "ALPA CORRAL",
      "LAS JUNTURAS",
      "EL BRETE",
      "PIQUILLIN",
      "CAMINIAGA",
      "CAÑADA DEL SAUCE",
      "ALTO DE LOS QUEBRACHOS",
      "LA RINCONADA",
      "EL CRISPIN",
      "AGUA DE ORO",
      "GENERAL ROCA",
      "COLONIA VICENTE AGUERO",
      "TRANSITO",
      "LUTTI",
      "LAS ACEQUIAS",
      "VILLA NUEVA",
      "SAN PEDRO NORTE",
      "CAPILLA DEL MONTE",
      "PAMPAYASTA NORTE",
      "GUTEMBERG",
      "GENERAL FOTHERINGHAM",
      "PORTEÑA",
      "MONTE CRISTO",
      "CAPITAN GENERAL BERNARDO O HIGGINS",
      "SAN VICENTE",
      "VILLA CURA BROCHERO",
      "CHANCANI",
      "LAS PALMAS",
      "CHUÑA",
      "COLONIA BARGE",
      "ROSALES",
      "LAS GRAMILLAS",
      "VILLA YACANTO",
      "CAÑADA DE MACHADO",
      "BENGOLEA",
      "LA QUINTA",
      "EL RASTREADOR",
      "LAS CALERAS",
      "TOSQUITA",
      "PUEBLO ITALIANO",
      "LOS HOYOS",
      "CAÑADA DE LUQUE",
      "PLAZA LUXARDO",
      "CABALANGO",
      "LAS VERTIENTES",
      "LAGUNA LARGA",
      "ARROYO CABRAL",
      "MATTALDI",
      "LA PAMPA",
      "CHARRAS",
      "PILAR",
      "JESUS MARIA",
      "ONCATIVO",
      "COLONIA VIDELA",
      "SAN JOAQUIN",
      "ESTACION JUAREZ CELMAN",
      "KILOMETRO 658",
      "LAS SALADAS",
      "ROSARIO DEL SALADILLO",
      "INRIVILLE",
      "EL TIO",
      "LOS CISNES",
      "VILLA ASCASUBI",
      "SANTA ROSA DE RIO PRIMERO",
      "OLIVA",
      "ORDOÑEZ",
      "VILLA CARLOS PAZ",
      "DESPEÑADEROS",
      "GENERAL CABRERA",
      "GENERAL BALDISSERA",
      "COLONIA ITURRASPE",
      "ANISACATE",
      "EMBALSE",
      "SAIRA",
      "CHILIBROSTE",
      "MATORRALES",
      "ALTO ALEGRE",
      "CORONEL BAIGORRIA",
      "MARULL",
      "VILLA GENERAL BELGRANO",
      "LAS HIGUERAS",
      "VILLA SARMIENTO",
      "LA PLAYOSA",
      "LA PLAYA",
      "LUCIO VICTORIO MANSILLA",
      "TALAINI",
      "COLONIA BISMARCK",
      "ADELIA MARIA",
      "WENCESLAO ESCALANTE",
      "RIO SEGUNDO",
      "COLONIA LAS PICHANAS",
      "LAS VARAS",
      "CHAJAN",
      "COSQUIN",
      "LA PAQUITA",
      "LAS ISLETILLAS",
      "CINTRA",
      "SAN ROQUE",
      "SANTA MARIA DE PUNILLA",
      "SIMBOLAR",
      "ASSUNTA",
      "RINCON",
      "VILLA SANTA CRUZ DEL LAGO",
      "GENERAL DEHEZA",
      "VILLA LA BOLSA",
      "LOS HORNILLOS",
      "BERROTARAN",
      "CONLARA",
      "PAMPAYASTA SUD",
      "VILLA ROSSI",
      "LUQUE",
      "COPACABANA",
      "MONTE RALO",
      "CORONEL MOLDES",
      "VILLA GIARDINO",
      "VILLA GUTIERREZ",
      "MORRISON",
      "LA POSTA",
      "LAS PERDICES",
      "ELENA",
      "JAMES CRAIK",
      "CARRILOBO",
      "VILLA PARQUE SIQUIMAN",
      "UCACHA",
      "MI GRANJA",
      "POZO NUEVO",
      "RAYO CORTADO",
      "CHARBONIER",
      "LAS RABONAS",
      "EL CHACHO",
      "CRUZ DEL EJE",
      "MINA CLAVERO",
      "SAN FRANCISCO",
      "CAPILLA DEL SITON",
      "LOS CEDROS",
      "CORRALITO",
      "RIO PRIMERO",
      "OBISPO TREJO",
      "CAMILO ALDAO",
      "BAÑADO DE SOTO",
      "RAFAEL GARCIA",
      "BALNEARIA",
      "COLONIA ALMADA",
      "LAS BAJADAS",
      "PASO DEL DURAZNO",
      "LOS POZOS",
      "LAS PLAYAS",
      "SUCO",
      "PACHECO DE MELO",
      "PINCEN",
      "CALCHIN OESTE",
      "MIRAMAR",
      "VILLA AMANCAY",
      "PANAHOLMA",
      "ESTACION GENERAL PAZ",
      "IDIAZABAL",
      "COLONIA PROSPERIDAD",
      "COMECHINGONES",
      "VILLA SAN ESTEBAN",
      "SAN JOSE",
      "VILLA LOS PATOS",
      "HUANCHILLA",
      "TANCACHA",
      "ITALO",
      "RIOBAMBA",
      "ESQUINA",
      "RANQUELES",
      "MARCOS JUAREZ",
      "SATURNINO MARIA LASPIUR",
      "ALEJANDRO ROCA",
      "VILLA QUILLINZO",
      "MEDIA NARANJA",
      "PASO VIEJO",
      "LAS CAÑADAS",
      "LAS PEÑAS SUD",
      "SANTIAGO TEMPLE",
      "AMBUL",
      "ALTOS DE CHIPION",
      "LAS ALBAHACAS",
      "VILLA PARQUE SANTA ANA",
      "ARROYO ALGODON",
      "SAN MARCOS SUD",
      "SEEBER",
      "HUERTA GRANDE",
      "EUFRASIO LOZA",
      "JOVITA",
      "SANTA EUFEMIA",
      "SAN FRANCISCO DEL CHAÑAR",
      "VIAMONTE",
      "MONTE DE LOS GAUCHOS",
      "LA CARLOTA",
      "COLONIA VALTELINA",
      "CRUZ ALTA",
      "CHAZON",
      "VILLA TULUMBA",
      "LOS CERRILLOS",
      "COLONIA SAN BARTOLOME",
      "VILLA CANDELARIA NORTE",
      "FALDA DEL CARMEN",
      "TUCLAME",
      "VILLA DE SOTO",
      "VILLA DE LAS ROSAS",
      "LABOULAYE",
      "BIALET MASSE",
      "LA CAUTIVA",
      "SAN PEDRO",
      "GENERAL LEVALLE",
      "RIO DE LOS SAUCES",
      "HERNANDO",
      "COLONIA LAS CUATRO ESQUINAS",
      "POZO DEL MOLLE",
      "LA CAROLINA EL POTOSI",
      "LA HIGUERA",
      "MALVINAS ARGENTINAS",
      "LA CUMBRECITA",
      "ALTA GRACIA",
      "NOETINGER",
      "COLONIA ANITA",
      "PLAZA DE MERCEDES",
      "ALCIRA",
      "COLONIA CAROYA",
      "VILLA DEL ROSARIO",
      "CHALACEA",
      "SACANTA",
      "MAYU SUMAJ",
      "VILLA MARIA",
      "SAN MARCOS SIERRAS",
      "SAN JAVIER Y YACANTO",
      "VILLA ALLENDE",
      "NICOLAS BRUZZONE",
      "LA CRUZ",
      "DIQUE CHICO",
      "MALENA",
      "PUNTA DEL AGUA",
      "SERRANO",
      "SAN CLEMENTE",
      "COLONIA MARINA",
      "VILLA CONCEPCION DEL TIO",
      "COLONIA BREMEN",
      "EL MANZANO",
      "VILLA ELISA",
      "VILLA LOS AROMOS",
      "TANTI",
      "RIO CUARTO",
      "LOS SURGENTES",
      "TALA HUASI",
      "SAN BASILIO",
      "IMPIRA",
      "SAGRADA FAMILIA",
      "DIEGO DE ROJAS",
      "CANDELARIA SUD",
      "LA FALDA",
      "PASCANAS",
      "SEBASTIAN ELCANO",
      "LA POBLACION",
      "SAN CARLOS MINAS",
      "UNQUILLO",
      "CANALS",
      "SALADILLO",
      "COLAZO",
      "LOS CHAÑARITOS (CRUZ DEL EJE)",
      "COLONIA ITALIANA",
      "CALMAYO",
      "SANTA CATALINA",
      "BUCHARDO",
      "LAS CALLES",
      "LA GRANJA",
      "LOS REARTES",
      "GUANACO MUERTO",
      "LA LAGUNA",
      "MONTE BUEY",
      "VILLA CIUDAD PARQUE LOS REARTES",
      "VILLA DE POCHO",
      "LA PAZ",
      "TOLEDO",
      "CHAÑAR VIEJO",
      "VILLA CIUDAD DE AMERICA",
      "SAN IGNACIO",
      "BOUWER",
      "SAN LORENZO",
      "LA CESIRA",
      "LA CALERA",
      "SERREZUELA",
      "DEVOTO",
      "SILVIO PELLICO",
      "BALLESTEROS",
      "ETRURIA",
      "JUSTINIANO POSSE",
      "ALICIA",
      "WASHINGTON",
      "SAN JOSE DE LA DORMIDA",
      "ALDEA SANTA MARIA",
      "SANTA ELENA",
      "REDUCCION",
      "VILLA DOLORES",
      "ANA ZUMARAN",
      "LA SERRANITA",
      "LOS MOLINOS",
      "RIO CEBALLOS",
      "EL ARAÑADO",
      "CAÑADA DE RIO PINTO",
      "GUASAPAMPA",
      "NONO",
      "LA FRANCIA",
      "RIO TERCERO",
      "QUEBRACHO HERRADO",
      "SEGUNDA USINA",
      "COSTA SACATE",
      "ARROYITO",
      "LAS TAPIAS",
      "LA PARA",
      "CRUZ DE CAÑA",
      "TALA CAÑADA",
      "CIENAGA DEL CORO",
      "VALLE DE ANISACATE",
      "OLAETA",
      "SAN ANTONIO DE ARREDONDO",
      "CHUÑA HUASI",
      "SAN ANTONIO DE LITIN",
      "PUESTO DE CASTRO",
      "MONTE LEÑA",
      "CASA GRANDE",
      "VILLA VALERIA",
      "HUINCA RENANCO",
      "LAS ARRIAS",
      "VILLA DEL TOTORAL",
      "EL RODEO",
      "CORDOBA",
      "VILLA SAN ISIDRO",
      "FREYRE",
      "SAMPACHO",
      "MENDIOLAZA",
      "LA TORDILLA",
      "TOSNO",
      "EL FORTIN",
      "AUSONIA",
      "LAS VARILLAS",
      "LEGUIZAMON",
      "PASCO",
      "MORTEROS",
      "TINOCO",
      "DALMACIO VELEZ",
      "CHUCUL",
      "VALLE HERMOSO",
      "CAPILLA DE LOS REMEDIOS",
      "BENJAMIN GOULD",
      "ACHIRAS",
      "COLONIA SAN PEDRO",
      "VICUÑA MACKENNA",
      "POTRERO DE GARAY",
      "CAPILLA DEL CARMEN",
      "ARIAS",
      "VILLA CERRO AZUL",
      "CALCHIN",
      "LOS COCOS",
      "VILLA RUMIPAL",
      "ESTANCIA VIEJA",
      "LA PALESTINA",
      "BRINKMANN",
      "OLIVARES DE SAN NICOLAS",
      "TIO PUJIO",
      "VILLA FONTANA",
      "ALMAFUERTE",
      "CHURQUI CAÑADA",
      "CORRAL DE BUSTOS",
      "LOS MISTOLES",
      "VILLA DE MARIA",
      "ATAHONA",
      "LA PAISANITA",
      "SARMIENTO",
      "LOS CONDORES",
      "DEL CAMPILLO",
      "COLONIA VIGNAUD",
      "SAUCE ARRIBA",
      "VILLA DEL DIQUE",
      "LUYABA",
      "VILLA EL CHACAY",
      "MAQUINISTA GALLINI",
      "SAN JOSE DE LAS SALINAS",
      "MELO",
      "BALLESTEROS SUD",
      "AVELLANEDA",
      "VILLA RIO ICHO CRUZ",
      "MALAGUEÑO",
      "BULNES",
      "LA BATEA",
      "SAN AGUSTIN",
    ],
    "CORRIENTES": [
      "LAVALLE",
      "EL SOMBRERO",
      "SAN ISIDRO",
      "PAGO DE LOS DESEOS",
      "3 DE ABRIL",
      "CAROLINA",
      "VILLA OLIVARI",
      "COLONIA PANDO",
      "CECILIO ECHAVARRIA",
      "CAZADORES CORRENTINOS",
      "9 DE JULIO",
      "SAN LUIS DEL PALMAR",
      "SAN ANTONIO ISLA APIPE GRANDE",
      "ESTACION TORRENT",
      "EMPEDRADO",
      "GOBERNADOR MARTINEZ",
      "SAN COSME",
      "CONCEPCION DEL YAGUARETE CORA",
      "ALVEAR",
      "PALMAR GRANDE",
      "MOCORETA",
      "CAA CATI",
      "ITATI",
      "CRUZ DE LOS MILAGROS",
      "BELLA VISTA",
      "ITUZAINGO",
      "TABAY",
      "TAPEBICUA",
      "ESQUINA",
      "PEDRO R FERNANDEZ",
      "ITA IBATE",
      "BONPLAND",
      "COLONIA CARLOS PELLEGRINI",
      "GOBERNADOR VIRASORO",
      "MONTE CASEROS",
      "SANTA ANA DE LOS GUÁCARAS",
      "COLONIA SANTA ROSA",
      "SALADAS",
      "LOMAS DE VALLEJOS",
      "SAN ROQUE",
      "SAN LORENZO",
      "YATAYTI CALLE",
      "PASO DE LOS LIBRES",
      "YAPEYU",
      "MARIANO I LOZA",
      "PERUGORRIA",
      "CHAVARRIA",
      "JUAN PUJOL",
      "CURUZU CUATIA",
      "COLONIA LIEBIG S",
      "MERCEDES",
      "RAMADA PASO",
      "TATACUA",
      "SANTO TOME",
      "SAN MIGUEL",
      "SANTA LUCIA",
      "PARADA PUCHETA",
      "BERÓN DE ASTRADA",
      "GOYA",
      "CORRIENTES",
      "GARAVI",
      "MBURUCUYA",
      "GUAVIRAVI",
      "SAUCE",
      "SAN CARLOS",
      "PASO DE LA PATRIA",
      "RIACHUELO",
      "COLONIA LIBERTAD",
      "LORETO",
      "LA CRUZ",
      "FELIPE YOFRE",
      "GARRUCHOS",
      "PUEBLO LIBERTADOR",
      "HERLITZKA",
    ],
    "ENTRE RÍOS": [
      "LOS CONQUISTADORES",
      "GENERAL GALARZA",
      "SAN RAMIREZ",
      "NUEVA VIZCAYA",
      "ENRIQUE CARBO",
      "EL CARMEN - ESTACION RACEDO",
      "LUCAS SUR PRIMERO",
      "COLONIA SAN ANSELMO Y ALEDAÑAS",
      "COSTA GRANDE",
      "LA FLORIDA",
      "SAN ROQUE",
      "BANDERAS",
      "DISTRITO DIEGO LOPEZ",
      "SANTA LUCIA",
      "DISTRITO CHAÑAR",
      "LAS MULITAS",
      "ISLAS LAS LECHIGUANAS",
      "PASTOR BRITOS",
      "RINCON DEL GATO",
      "PERDICES",
      "ÑANCAY",
      "LA PROVIDENCIA",
      "SAUCECITO",
      "CRUCESITAS OCTAVA",
      "ORO VERDE",
      "ARROYO CORRALITO",
      "ALDEA SANTA ROSA",
      "COLONIA OFICIAL N° 5",
      "ARROYO GENA",
      "SAN CIPRIANO",
      "TALA",
      "CHILCAS",
      "HINOJAL",
      "RINCON DEL DOLL",
      "MONTOYA",
      "COLONIA ADIVINO",
      "PARAJE LOS ALGARROBOS",
      "SAN MIGUEL",
      "ALBARDON - PUNTA DEL MONTE",
      "DISTRITO TALA",
      "COLONIA REFFINO",
      "ESTACION YUQUERI",
      "EL GATO - LOMA LIMPIA",
      "COLONIA OFICIAL N° 13",
      "GONZALEZ CALDERON",
      "LAS TOSCAS",
      "CRUCESITAS TERCERA",
      "COSTA URUGUAY SUR",
      "MONTE REDONDO (O 7° DISTRITO)",
      "COLONIA TUNAS",
      "SAUCE SUR",
      "COLONIA ENSAYO",
      "VILLA DEL ROSARIO",
      "ALDEA SAN JUAN",
      "ALTAMIRANO SUR",
      "SOSA",
      "GUALEGUAYCITO",
      "CONCEPCION DEL URUGUAY",
      "GENERAL ALMADA",
      "GOBERNADOR FEBRE",
      "AREA SIN GOBIERNO",
      "SAN VICTOR",
      "PUEBLO CAZES",
      "PARANA",
      "GENERAL CAMPOS",
      "LAGUNA BENITEZ",
      "VILLA URQUIZA",
      "EL PALENQUE",
      "VILLAGUAY",
      "PEDERNAL",
      "JUBILEO",
      "SANTA ANA",
      "IRAZUSTA",
      "ALCARAZ",
      "EL CIMARRON",
      "ANTELO",
      "SAN ERNESTO",
      "PICADA BERON",
      "LUCAS NORTE",
      "DISTRITO SEXTO COSTA DE NOGOYA",
      "DISTRITO CHIQUEROS",
      "HERNANDARIAS",
      "CERRITO",
      "LAS TUNAS",
      "WALTER MOSS",
      "TABOSSI",
      "MOJONES NORTE",
      "COLONIA CRESPO",
      "CONCORDIA",
      "LAS MERCEDES",
      "ALCARAZ NORTE",
      "PUEBLO BRUGO",
      "ESTACION LIBAROS",
      "ESTACION ESCRIÑA",
      "HOCKER",
      "ESTACION RAICES",
      "CUCHILLA REDONDA",
      "URDINARRAIN",
      "MARIA GRANDE 2°",
      "DON CRISTOBAL PRIMERO",
      "COLONIA SANTA MARIA Y LAS MARGARITAS",
      "COLONIA VIRARO",
      "ALDEA EIGENFELD",
      "CEIBAS",
      "PARAJE GUAYAQUIL",
      "PASO DE LAS PIEDRAS",
      "ALDEA VALLE MARIA",
      "SAN SALVADOR",
      "SANTA ANITA",
      "VILLA FONTANA",
      "COLONIA AVELLANEDA",
      "NOGOYA",
      "EL REDOMON",
      "GUALEGUAYCHU",
      "VILLA PARANACITO",
      "ISLETAS",
      "LUCAS GONZALEZ",
      "LAS GUACHAS",
      "SAN JOSE DE FELICIANO",
      "GOBERNADOR ECHAGUE",
      "SAN MARCIAL",
      "LUCAS SUR SEGUNDO",
      "MOJONES SUR",
      "SAN BENITO",
      "PASO DE LA ARENA",
      "MULAS GRANDES",
      "PUEBLO GENERAL BELGRANO",
      "DON CRISTOBAL SEGUNDO",
      "PUERTO ALGARROBO",
      "LA CLARITA",
      "COLONIA SAN JUSTO",
      "DIAMANTE",
      "ESTACION LAZO",
      "LA VERBENA",
      "BASAVILBASO",
      "ALDEA SPATZENKUTTER",
      "COLONIA CELINA",
      "LA FRATERNIDAD Y SANTA JUANA",
      "XX DE SETIEMBRE",
      "INGENIERO SAJAROFF",
      "COLONIA BAYLINA",
      "COLONIA AVIGDOR",
      "LA ESMERALDA",
      "NUEVA ESCOCIA",
      "QUEBRACHO",
      "SEGUI",
      "SAN PEDRO",
      "CONSCRIPTO BERNARDI",
      "TEZANOS PINTO",
      "ANTONIO TOMAS",
      "SAN JUSTO",
      "LA PAZ",
      "ALDEA SALTO",
      "VIALE",
      "ALDEA GRAPSCHENTAL",
      "MOLINO DOLL",
      "LAS GARZAS",
      "GOBERNADOR MANSILLA",
      "PIEDRAS BLANCAS",
      "LA OLLITA",
      "RAICES OESTE",
      "VILLA ELISA",
      "COLONIA MEROU",
      "SAN RAMON",
      "HASENKAMP",
      "ESPINILLO NORTE",
      "SIR LEONARD",
      "ROCAMORA",
      "PASO DUARTE",
      "COLONIA CARRASCO",
      "ALDEA SAN ANTONIO",
      "ESTAQUITAS",
      "MACIA",
      "LA HIERRA",
      "GUARDAMONTE",
      "ALDEA BRASILERA",
      "VILLA MANTERO",
      "FEDERAL",
      "SANTA LUISA",
      "LA PICADA",
      "FAUSTINO M PARERA",
      "LAGUNA DEL PESCADO",
      "ARANGUREN",
      "EL QUEBRACHO",
      "MEDANOS",
      "MARIA GRANDE",
      "ESTACION CAMPS",
      "DURAZNO",
      "1° DE MAYO",
      "RINCON DE NOGOYA",
      "VILLA LIBERTADOR SAN MARTIN",
      "SAN JAIME DE LA FRONTERA",
      "ALDEA PROTESTANTE",
      "GUALEGUAY",
      "YESO OESTE",
      "IBICUY",
      "SAUCE MONTRULL",
      "PRONUNCIAMIENTO",
      "GENERAL RAMIREZ",
      "ROSARIO DEL TALA",
      "HERRERA",
      "ALCARAZ SUR",
      "HERNANDEZ",
      "PUEBLO LIEBIG S",
      "EL GRAMIYAL",
      "CRESPO",
      "LOS CHARRUAS",
      "LAS MOSCAS",
      "ALDEA SANTA MARIA",
      "ALDEA SAN RAFAEL",
      "SAN GUSTAVO",
      "ARROYO BARU",
      "COSTA URUGUAY NORTE",
      "BETBEDER",
      "VILLA CLARA",
      "COLONIA GENERAL ROCA",
      "ESTACION YERUA",
      "OMBU",
      "SAN JOSE",
      "ALDEA MARIA LUISA",
      "GENERAL ALVEAR",
      "COLON",
      "YACARE",
      "ESTANCIA GRANDE",
      "LAS CUEVAS",
      "ALDEA ASUNCION",
      "DISTRITO PRIMERO (PRIMER DISTRITO CUCHILLA)",
      "COLONIA OFICIAL N° 3 Y 14",
      "CURTIEMBRE",
      "SANTA ELENA",
      "EL SOLAR, SAN CARLOS Y COLONIA BERTOZZI",
      "BOVRIL",
      "LARROQUE",
      "PAJONAL",
      "LAURENCENA",
      "PASO DE LA LAGUNA",
      "CHAJARI",
      "CLODOMIRO LEDESMA",
      "COLONIA AYUI",
      "ARROYO DEL MEDIO",
      "PUERTO YERUA",
      "COLONIA ELIA",
      "SAUCE PINTO",
      "COLONIA ALEMANA",
      "EL PINGO",
      "ARROYO BURGOS",
      "UBAJAY",
      "SAUCE DE LUNA",
      "VILLA GOBERNADOR ETCHEVEHERE",
      "GILBERT",
      "LA CRIOLLA",
      "HAMBIS",
      "VILLA DOMINGUEZ",
      "DISTRITO TALITAS",
      "VICTORIA",
      "FEDERACION",
      "ALDEA SAN MIGUEL",
      "CASEROS",
      "ARROYO CLE",
      "GOBERNADOR SOLA",
    ],
    "FORMOSA": [
      "FORMOSA",
      "POSTA CAMBIO ZALAZAR",
      "AREA SIN GOBIERNO",
      "IBARRETA",
      "JUAN G BAZAN",
      "ESTANISLAO DEL CAMPO",
      "VILLA DOS TRECE",
      "BUENA VISTA",
      "MISION SAN FRANCISCO DE LAISHI",
      "LAGUNA GALLO",
      "EL COLORADO",
      "SAN MARTIN I",
      "COLONIA SARMIENTO",
      "MOJON DE FIERRO",
      "TRES LAGUNAS",
      "RIACHO NEGRO",
      "EL RECREO",
      "COLONIA PASTORIL",
      "SAN HILARIO",
      "VILLA ESCOLAR",
      "PORTON NEGRO",
      "MISION TACAAGLE",
      "PALO SANTO",
      "SIETE PALMAS",
      "RIACHO HE-HE",
      "EL POTRILLO",
      "BANCO PAYAGUA",
      "PALMA SOLA",
      "GENERAL MOSCONI",
      "TATANE",
      "POZO DE MAZA",
      "VILLA GENERAL GUEMES",
      "VILLA DEL CARMEN",
      "LAS LOMITAS",
      "MARIANO BOEDO",
      "INGENIERO GUILLERMO NICASIO JUAREZ",
      "POZO DEL TIGRE",
      "GRAN GUARDIA",
      "SAN MARTIN DOS",
      "CLORINDA",
      "GENERAL BELGRANO",
      "SUBTENIENTE PERIN",
      "PIRANE",
      "POZO DEL MORTERO",
      "LAGUNA NAICK NECK",
      "GENERAL LUCIO V MANSILLA",
      "MAYOR VICENTE E",
      "FORTIN SARGENTO 1° LEYES",
      "LAGUNA YEMA",
      "BARTOLOME DE LAS CASAS",
      "FORTIN CABO 1°  LUGONES",
      "LAGUNA BLANCA",
      "COMANDANTE FONTANA",
      "LOS CHIRIGUANOS",
      "HERRADURA",
      "EL ESPINILLO",
    ],
    "JUJUY": [
      "BARRANCAS",
      "HUACALERA",
      "TUMBAYA",
      "CALILEGUA",
      "LA ESPERANZA",
      "PERICO",
      "PALMA SOLA",
      "CUSI CUSI",
      "SAN SALVADOR DE JUJUY",
      "ABRALAITE",
      "LIBERTADOR GENERAL SAN MARTIN",
      "PURMAMARCA",
      "CASPALA",
      "TILCARA",
      "ROSARIO DE RIO GRANDE",
      "CATUA",
      "SAN FRANCISCO",
      "AGUAS CALIENTES",
      "CORANZULI",
      "EL AGUILAR",
      "SAN ANTONIO",
      "EL CONDOR",
      "CAIMANCITO",
      "EL CARMEN",
      "PAMPICHUELA",
      "RODEITO",
      "ARRAYANAL",
      "YAVI",
      "SANTA CATALINA",
      "SANTA ANA",
      "PAMPA BLANCA",
      "BARRIOS",
      "CANGREJILLOS",
      "MONTERRICO",
      "MAIMARA",
      "EL FUERTE",
      "LA MENDIETA",
      "VOLCAN",
      "ABRA PAMPA",
      "SAN PEDRO DE JUJUY",
      "VINALITO",
      "HUMAHUACA",
      "TRES CRUCES",
      "VALLE GRANDE",
      "PUESTO DEL MARQUEZ",
      "MINA PIRQUITAS",
      "SANTA CLARA",
      "LA QUIACA",
      "PALPALA",
      "EL PIQUETE",
      "PUMAHUASI",
      "RINCONADA",
      "YALA",
      "YUTO",
      "EL TALAR",
      "PUESTO VIEJO",
      "HIPOLITO YRIGOYEN",
      "SUSQUES",
      "CIENEGUILLAS",
      "FRAILE PINTADO",
    ],
    "LA PAMPA": [
      "PUELCHES",
      "CHACHARRAMENDI",
      "ALTA ITALIA",
      "SANTA ROSA",
      "TOAY",
      "MAISONAVE",
      "PUELEN",
      "MAURICIO MAYER",
      "REALICO",
      "WINIFREDA",
      "PARERA",
      "LIMAY MAHUIDA",
      "QUETREQUEN",
      "MIGUEL CANE",
      "BERNARDO LARROUDE",
      "BERNASCONI",
      "SARAH",
      "INTENDENTE ALVEAR",
      "LONQUIMAY",
      "SPELUZZI",
      "GENERAL SAN MARTIN",
      "LUAN TORO",
      "PICHI HUINCA",
      "FALUCHO",
      "LA MARUJA",
      "CUCHILLO CO",
      "ABRAMO",
      "RANCUL",
      "ALPACHIRI",
      "QUEMU QUEMU",
      "MACACHIN",
      "MONTE NIEVAS",
      "LA ADELA",
      "DORILA",
      "ALGARROBO DEL AGUILA",
      "GUATRACHE",
      "TRENEL",
      "CALEUFU",
      "LA HUMADA",
      "CARRO QUEMADO",
      "COLONIA SANTA TERESA",
      "ADOLFO VAN PRAET",
      "COLONIA SANTA MARIA",
      "ATALIVA ROCA",
      "GENERAL ACHA",
      "UNANUE",
      "GENERAL PICO",
      "INGENIERO LUIGGI",
      "RELMO",
      "VICTORICA",
      "CATRILO",
      "ARATA",
      "CORONEL HILARIO LAGOS",
      "LA REFORMA",
      "GOBERNADOR DUVAL",
      "COLONIA BARON",
      "EMBAJADOR MARTINI",
      "GENERAL CAMPOS",
      "MIGUEL RIGLOS",
      "LOVENTUE",
      "CONHELO",
      "TOMAS M ANCHORENA",
      "ROLON",
      "TELEN",
      "VILLA MIRASOL",
      "EDUARDO CASTEX",
      "CASA DE PIEDRA",
      "VERTIZ",
      "ANGUIL",
      "URIBURU",
      "AGUSTONI",
      "SANTA ISABEL",
      "COLONIA 25 DE MAYO",
      "QUEHUE",
      "RUCANELO",
      "CEBALLOS",
      "PERU",
      "JACINTO ARAUZ",
      "METILEO",
      "DOBLAS",
    ],
    "LA RIOJA": [
      "SANAGASTA",
      "ARAUCO",
      "CHAMICAL",
      "GENERAL OCAMPO",
      "SAN BLAS DE LOS SAUCES",
      "GENERAL BELGRANO",
      "ROSARIO VERA PEÑALOZA",
      "CHILECITO",
      "VINCHINA",
      "FAMATINA",
      "CAPITAL",
      "GENERAL LAMADRID",
      "CORONEL FELIPE VARELA",
      "GENERAL JUAN F QUIROGA",
      "GENERAL SAN MARTIN",
      "INDEPENDENCIA",
      "CASTRO BARROS",
      "GENERAL ANGEL V PEÑALOZA",
    ],
    "MENDOZA": [
      "MALARGUE",
      "SAN CARLOS",
      "SAN MARTIN",
      "LA PAZ",
      "LAVALLE",
      "SANTA ROSA",
      "GENERAL ALVEAR",
      "LAS HERAS",
      "CAPITAL",
      "GUAYMALLEN",
      "GODOY CRUZ",
      "MAIPU",
      "TUPUNGATO",
      "LUJAN DE CUYO",
      "TUNUYAN",
      "RIVADAVIA",
      "JUNIN",
      "SAN RAFAEL",
    ],
    "MISIONES": [
      "GARUHAPE",
      "POZO AZUL",
      "SALTO ENCANTADO",
      "TRES CAPONES",
      "SAN JOSE",
      "GENERAL URQUIZA",
      "CAMPO VIERA",
      "MOJON GRANDE",
      "CERRO CORA",
      "AZARA",
      "OBERA",
      "CONCEPCION DE LA SIERRA",
      "COLONIA VICTORIA",
      "PROFUNDIDAD",
      "9 DE JULIO",
      "COLONIA DELICIA",
      "GOBERNADOR ROCA",
      "OLEGARIO VICTOR ANDRADE",
      "CAMPO RAMON",
      "MONTECARLO",
      "EL SOBERBIO",
      "PUERTO IGUAZU",
      "BONPLAND",
      "SAN JAVIER",
      "LEANDRO N ALEM",
      "POSADAS",
      "MARTIRES",
      "ALBA POSSE",
      "DOS ARROYOS",
      "COLONIA ALBERDI",
      "ALMAFUERTE",
      "CORPUS",
      "SANTIAGO DE LINIERS",
      "CERRO AZUL",
      "GENERAL ALVEAR",
      "LORETO",
      "JARDIN AMERICA",
      "SAN VICENTE",
      "GARUPA",
      "SANTA MARIA",
      "COLONIA POLANA",
      "EL ALCAZAR",
      "CAMPO GRANDE",
      "CANDELARIA",
      "SAN IGNACIO",
      "ARROYO DEL MEDIO",
      "FACHINAL",
      "COLONIA AURORA",
      "25 DE MAYO",
      "PUERTO RICO",
      "GOBERNADOR LOPEZ",
      "SANTA ANA",
      "PUERTO LIBERTAD",
      "PUERTO PIRAY",
      "GUARANI",
      "CARAGUATAY",
      "SANTO PIPO",
      "WANDA",
      "PUERTO LEONI",
      "HIPOLITO YRIGOYEN",
      "PUERTO ESPERANZA",
      "SAN MARTIN",
      "CAPIOVI",
      "ITACARUARE",
      "ELDORADO",
      "SAN PEDRO",
      "SAN ANTONIO",
      "FLORENTINO AMEGHINO",
      "ANDRESITO",
      "ARISTOBULO DEL VALLE",
      "RUIZ DE MONTOYA",
      "CAA YARI",
      "APOSTOLES",
      "LOS HELECHOS",
      "BERNARDO DE IRIGOYEN",
      "DOS DE MAYO",
      "PANAMBI",
    ],
    "NEUQUÉN": [
      "VISTA ALEGRE",
      "PILO LIL",
      "GUAÑACOS",
      "VILLA LAGO MELIQUINA",
      "SENILLOSA",
      "TRICAO MALAL",
      "LONCOPUE",
      "NEUQUEN",
      "AREA SIN GOBIERNO",
      "PIEDRA DEL AGUILA",
      "VILLA DEL NAHUEVE",
      "AÑELO",
      "HUINGANCO",
      "VILLA LA ANGOSTURA",
      "SAUZAL BONITO",
      "LOS MICHES",
      "BUTA RANQUIL",
      "TAQUIMILAN",
      "VILLA PEHUENIA",
      "PLOTTIER",
      "VILLA PUENTE PICUN LEUFU",
      "COYUCO COCHICO",
      "BAJADA DEL AGRIO",
      "LOS CHIHUIDOS",
      "RAMON M CASTRO",
      "PASO AGUERRE",
      "VARVARCO - INVERNADA VIEJA",
      "LAS OVEJAS",
      "CENTENARIO",
      "MARIANO MORENO",
      "BARRANCAS",
      "RINCON DE LOS SAUCES",
      "JUNIN DE LOS ANDES",
      "SAN MARTIN DE LOS ANDES",
      "LOS CATUTOS",
      "ZAPALA",
      "MANZANO AMARGO",
      "CUTRAL CO",
      "PLAZA HUINCUL",
      "VILLA TRAFUL",
      "CAVIAHUE - COPAHUE",
      "AGUADA SAN ROQUE",
      "QUILI MALAL",
      "OCTAVIO PICO",
      "SANTO TOMAS",
      "COVUNCO ABAJO",
      "VILLA EL CHOCON",
      "SAN PATRICIO DEL CHAÑAR",
      "EL SAUCE",
      "CHORRIACA",
      "ANDACOLLO",
      "EL CHOLAR",
      "CHOS MALAL",
      "ALUMINE",
      "LAS LAJAS",
      "VILLA CURI LEUVU",
      "LAS COLORADAS",
      "EL HUECU",
      "PICUN LEUFU",
    ],
    "RÍO NEGRO": [
      "NAUPA HUEN",
      "MAQUINCHAO",
      "AREA SIN GOBIERNO",
      "ARROYO LOS BERROS",
      "PASO FLORES",
      "CUBANEA",
      "CHIPAUQUIL",
      "PICHI MAHUIDA",
      "LAS GRUTAS",
      "ARROYO VENTANA",
      "CONTRALMIRANTE CORDERO",
      "PILQUINIYEU",
      "VILLA MASCARDI",
      "CINCO SALTOS",
      "INGENIERO JACOBACCI",
      "LAGUNA BLANCA",
      "SAN CARLOS DE BARILOCHE",
      "INGENIERO HUERGO",
      "GENERAL ENRIQUE GODOY",
      "CIPOLLETTI",
      "NAHUEL NIYEU",
      "EL CAIN",
      "GUARDIA MITRE",
      "OJOS DE AGUA",
      "DARWIN",
      "RIO CHICO",
      "CATRIEL",
      "PILCANIYEU",
      "CHELFORO",
      "MAINQUE",
      "GENERAL CONESA",
      "COMICO",
      "CLEMENTE ONELLI",
      "EL CUY",
      "VILLA LLANQUIN",
      "RIO COLORADO",
      "SAN JAVIER",
      "CERVANTES",
      "AGUADA DE GUERRA",
      "PEÑAS BLANCAS",
      "ÑORQUINCO",
      "MAMUEL CHOIQUE",
      "DINA HUAPI",
      "GENERAL ROCA",
      "VALLE AZUL",
      "CERRO POLICIA",
      "VILLA REGINA",
      "LAMARQUE",
      "COLAN CONUE",
      "VALCHETA",
      "AGUADA CECILIO",
      "RINCON TRENETA",
      "MINISTRO RAMOS MEXIA",
      "LOS MENUCOS",
      "EL MANSO",
      "SIERRA COLORADA",
      "SAN ANTONIO OESTE",
      "EL BOLSON",
      "GENERAL FERNANDEZ ORO",
      "CHIMPAY",
      "CONA NIYEU",
      "LUIS BELTRAN",
      "CAMPO GRANDE",
      "POMONA",
      "MENCUE",
      "CORONEL BELISLE",
      "COMALLO",
      "SIERRA GRANDE",
      "YAMINUE",
      "VIEDMA",
      "CHOELE CHOEL",
      "SIERRA PAILEMAN",
      "CHICHINALES",
      "PILQUINIYEU DEL LIMAY",
      "ALLEN",
      "PRAHUANIYEU",
      "AGUADA GUZMAN",
    ],
    "SALTA": [
      "LA CALDERA",
      "SANTA VICTORIA OESTE",
      "RIO PIEDRAS",
      "EL JARDIN",
      "CAFAYATE",
      "AGUAS BLANCAS",
      "EL TALA",
      "JOAQUIN V GONZALEZ",
      "GENERAL PIZARRO",
      "GENERAL MOSCONI",
      "CHICOANA",
      "NAZARENO",
      "RIVADAVIA BANDA NORTE",
      "EL BORDO",
      "EL GALPON",
      "AGUARAY",
      "EL QUEBRACHAL",
      "LA POMA",
      "SAN ANTONIO DE LOS COBRES",
      "TARTAGAL",
      "LA MERCED",
      "PROFESOR SALVADOR MAZZA",
      "VAQUEROS",
      "SECLANTAS",
      "ISLA DE CAÑAS",
      "ANIMANA",
      "EL CARRIL",
      "GUACHIPAS",
      "METAN",
      "LAS LAJITAS",
      "SALTA",
      "MOLINOS",
      "RIVADAVIA BANDA SUR",
      "EL POTRERO",
      "PAYOGASTA",
      "SAN LORENZO",
      "ANGASTACO",
      "SAN RAMON DE LA NUEVA ORAN",
      "CERRILLOS",
      "IRUYA",
      "LOS TOLDOS",
      "CORONEL MOLDES",
      "GENERAL BALLIVIAN",
      "ROSARIO DE LERMA",
      "PICHANAL",
      "TOLAR GRANDE",
      "COLONIA SANTA ROSA",
      "CAMPO QUIJANO",
      "CACHI",
      "HIPOLITO YRIGOYEN",
      "GENERAL GUEMES",
      "ROSARIO DE LA FRONTERA",
      "LA CANDELARIA",
      "EMBARCACION",
      "SAN CARLOS",
      "LA VIÑA",
      "CAMPO SANTO",
      "APOLINARIO SARAVIA",
      "SANTA VICTORIA ESTE",
      "URUNDEL",
    ],
    "SAN JUAN": [
      "ZONDA",
      "JACHAL",
      "POCITO",
      "CAUCETE",
      "CALINGASTA",
      "ULLUM",
      "SAN JUAN",
      "9 DE JULIO",
      "IGLESIA",
      "25 DE MAYO",
      "ANGACO",
      "VALLE FERTIL",
      "SARMIENTO",
      "RIVADAVIA",
      "SANTA LUCIA",
      "ALBARDON",
      "CHIMBAS",
      "RAWSON",
      "SAN MARTIN",
    ],
    "SAN LUIS": [
      "VILLA MERCEDES",
      "LAS AGUADAS",
      "LA TOMA",
      "LOS CAJONES",
      "ESTANCIA GRANDE",
      "QUINES",
      "CORTADERAS",
      "EL TRAPICHE",
      "LAS LAGUNAS",
      "CAROLINA",
      "VILLA LARCA",
      "AREA SIN GOBIERNO",
      "NACION RANQUEL",
      "ZANJITAS",
      "JUAN JORBA",
      "BAGUAL",
      "SALADILLO",
      "EL VOLCAN",
      "SAN LUIS",
      "LEANDRO N ALEM",
      "LA PUNILLA",
      "FORTIN EL PATRIA",
      "NAVIA",
      "VILLA DE PRAGA",
      "SAN PABLO",
      "VILLA LA FLORIDA",
      "SANTA ROSA DEL CONLARA",
      "UNION",
      "LAFINUR",
      "TILISARAO",
      "LA VERTIENTE",
      "CANDELARIA",
      "ALTO PENCOSO",
      "NOGOLI",
      "NASCHEL",
      "BUENA ESPERANZA",
      "FORTUNA",
      "LAS CHACRAS",
      "CARPINTERIA",
      "ARIZONA",
      "LOS MOLLES",
      "PASO GRANDE",
      "VILLA DEL CARMEN",
      "SAN MARTIN",
      "JUSTO DARACT",
      "VILLA DE LA QUEBRADA",
      "LAVAISSE",
      "SAN FRANCISCO DEL MONTE DE ORO",
      "BEAZLEY",
      "RENCA",
      "JUANA KOSLAY",
      "ALTO PELADO",
      "NUEVA GALIA",
      "JUAN LLERENA",
      "ANCHORENA",
      "PAPAGAYOS",
      "CONCARAN",
      "LUJAN",
      "LA PUNTA",
      "SAN JERONIMO",
      "VILLA DE MERLO",
      "TALITA",
      "POTRERO DE LOS FUNES",
      "DESAGUADERO",
      "SAN JOSE DEL MORRO",
      "BATAVIA",
      "FRAGA",
      "BALDE",
      "LA CALERA",
      "VILLA GENERAL ROCA",
    ],
    "SANTA CRUZ": [
      "EL CHALTEN",
      "CAÑADON SECO",
      "CALETA OLIVIA",
      "AREA SIN GOBIERNO",
      "LAS HERAS",
      "MINA 3",
      "LAGO POSADAS",
      "PUERTO DESEADO",
      "COMANDANTE LUIS PIEDRA BUENA",
      "NUESTRA SEÑORA DE LOS DOLORES DE KOLUEL KAIKE",
      "JARAMILLO - FITZ ROY",
      "RIO GALLEGOS",
      "PUERTO SAN JULIAN",
      "ROSPENTEK",
      "GOBERNADOR GREGORES",
      "PICO TRUNCADO",
      "TELLIER",
      "28 DE NOVIEMBRE",
      "BAJO CARACOLES",
      "EL TURBIO",
      "EL CALAFATE",
      "TRES LAGOS",
      "RIO TURBIO",
      "PUERTO SANTA CRUZ",
      "LOS ANTIGUOS",
      "JULIA DUFOUR",
      "PERITO MORENO",
    ],
    "SANTA FE": [
      "GODOY",
      "CORREA",
      "COLONIA ITURRASPE",
      "AREQUITO",
      "GENERAL LAGOS",
      "SUARDI",
      "SANTA CLARA DE BUENA VISTA",
      "LAS AVISPAS",
      "LABORDEBOY",
      "GENERAL GELLY",
      "EL TREBOL",
      "SANTA TERESA",
      "LANTERI",
      "COLONIA TERESA",
      "CAMPO PIAGGIO",
      "MAUA",
      "NICANOR MOLINAS",
      "DOS ROSAS Y LA LEGUA",
      "HARDY",
      "LOS TABANOS",
      "SANTO DOMINGO",
      "LOS CARDOS",
      "SANTA MARIA NORTE",
      "PALACIOS",
      "MONIGOTES",
      "PEDRO GOMEZ CELLO",
      "RAMONA",
      "LLAMBI CAMPBELL",
      "MONTES DE OCA",
      "SAN ANTONIO DE OBLIGADO",
      "CONSTANZA",
      "LOS LAURELES",
      "VILLA GUILLERMINA",
      "GATO COLORADO",
      "LAS PAREJAS",
      "CHABAS",
      "SANTA MARGARITA",
      "VILLA SAN JOSE",
      "SAN JAVIER",
      "NARE",
      "CAFERATA",
      "TOTORAS",
      "ESTEBAN RAMS",
      "POZO BORRADO",
      "MARIA SUSANA",
      "BERNA",
      "SALADERO MARIANO CABAL",
      "ALVEAR",
      "VILLA SARALEGUI",
      "VERA Y PINTADO",
      "LUIS PALACIOS",
      "SANTO TOME",
      "PUEBLO MARINI",
      "TOBA",
      "SAN MARTIN DE LAS ESCOBAS",
      "VILLA ELOISA",
      "FUNES",
      "SAN FRANCISCO DE SANTA FE",
      "DIAZ",
      "GRANADERO BAIGORRIA",
      "RAMAYON",
      "BARRANCAS",
      "GOBERNADOR CRESPO",
      "CLASSON",
      "CRISPI",
      "PROVIDENCIA",
      "PAVON",
      "LUCIO V LOPEZ",
      "ALVAREZ",
      "PEYRANO",
      "SAN CARLOS CENTRO",
      "FELICIA",
      "AGUARA GRANDE",
      "TIMBUES",
      "GESSLER",
      "MURPHY",
      "EMPALME VILLA CONSTITUCION",
      "CARRERAS",
      "ZENON PEREYRA",
      "PAVON ARRIBA",
      "VERA",
      "PUJATO",
      "RECONQUISTA",
      "EMPALME SAN CARLOS",
      "VILLA OCAMPO",
      "SAN CARLOS NORTE",
      "SAN JERONIMO DEL SAUCE",
      "TORTUGAS",
      "ARRUFO",
      "LA VANGUARDIA",
      "MARGARITA",
      "RIVADAVIA",
      "LAS PALMERAS",
      "FRAY LUIS BELTRAN",
      "BOMBAL",
      "COLONIA RAQUEL",
      "ITUZAINGO",
      "PIAMONTE",
      "LOS MOLINOS",
      "SAN GUILLERMO",
      "CERES",
      "AROCENA",
      "VILLA MINETTI",
      "JUAN DE GARAY",
      "PUERTO GENERAL SAN MARTIN",
      "PEREZ",
      "CANDIOTI",
      "COLONIA DURAN",
      "GOLONDRINA",
      "SASTRE",
      "GALVEZ",
      "CASTELLANOS",
      "CAÑADA ROSQUIN",
      "SAN ANTONIO",
      "TACUARENDI",
      "VILLA CAÑAS",
      "SILVA",
      "AMENABAR",
      "LA SARITA",
      "IBARLUCEA",
      "ANGELONI",
      "TACURAL",
      "ALDAO",
      "VENADO TUERTO",
      "SAN JOSE DEL RINCON",
      "MONTEFIORE",
      "GALISTEO",
      "LAGUNA PAIVA",
      "SUNCHALES",
      "GRUTLY",
      "SANTA FE",
      "MIGUEL TORRES",
      "HUANQUEROS",
      "COLONIA ROSA",
      "CAÑADA RICA",
      "SAN JORGE",
      "ÑANDUCITA",
      "COLONIA CELLO",
      "EUSEBIA Y CAROLINA",
      "SANTA CLARA DE SAGUIER",
      "CAÑADA OMBU",
      "HUGENTOBLER",
      "PUJATO NORTE",
      "SAN AGUSTIN",
      "COLONIA DOLORES",
      "GABOTO",
      "TARTAGAL",
      "BOUQUET",
      "PIÑERO",
      "LA PELADA",
      "AVELLANEDA",
      "PILAR",
      "CARRIZALES",
      "ESMERALDA",
      "PRESIDENTE ROCA",
      "CORONDA",
      "VILLADA",
      "CURUPAITY",
      "FIDELA",
      "RICARDONE",
      "EUSTOLIA",
      "ARMINDA",
      "CAPIVARA",
      "MALABRIGO",
      "SANTA MARIA CENTRO",
      "JUNCAL",
      "ARMSTRONG",
      "GODEKEN",
      "ELORTONDO",
      "LAS PETACAS",
      "ALEJANDRA",
      "ROSARIO",
      "CORONEL FRAGA",
      "EL ARAZA",
      "HERSILIA",
      "JACINTO L",
      "EL RABON",
      "SA PEREYRA",
      "COLONIA BELGRANO",
      "RECREO",
      "SUSANA",
      "COLONIA BOSSI",
      "COLONIA MASCIAS",
      "ELISA",
      "MARIA TERESA",
      "ATALIVA",
      "CAVOUR",
      "BERABEVU",
      "FUENTES",
      "PORTUGALETE",
      "SAN GREGORIO",
      "SOUTOMAYOR",
      "JUAN B MOLINA",
      "AARON CASTELLANOS",
      "INGENIERO CHANOURDIE",
      "LOS AMORES",
      "CHRISTOPHERSEN",
      "ARROYO SECO",
      "CASALEGNO",
      "SAGUIER",
      "TACURALES",
      "FIGHIERA",
      "ESPERANZA",
      "AMBROSETTI",
      "HUMBERTO PRIMO",
      "CORONEL BOGADO",
      "EGUSQUIZA",
      "LA PENCA Y CARAGUATA",
      "CHOVET",
      "COLONIA BICHA",
      "SANTURCE",
      "MARCELINO ESCALADA",
      "VILLA TRINIDAD",
      "CAMPO ANDINO",
      "MONJE",
      "FORTIN OLMOS",
      "MATILDE",
      "CASILDA",
      "CACIQUE ARIACAIQUIN",
      "SAN MARIANO",
      "RAFAELA",
      "SAN GENARO",
      "VILLA MUGUETA",
      "LA CABRAL",
      "SAN FABIAN",
      "ARROYO AGUIAR",
      "LA GALLARETA",
      "ROMANG",
      "VIRGINIA",
      "THEOBALD",
      "URANGA",
      "SANTA ISABEL",
      "BERNARDO DE IRIGOYEN",
      "LOS QUIRQUINCHOS",
      "CAYASTACITO",
      "HIPATIA",
      "LA LUCILA",
      "NELSON",
      "MARIA JUANA",
      "LAS BANDURRIAS",
      "WHEELWRIGHT",
      "VILLA AMELIA",
      "VILLA ANA",
      "VILLA GOBERNADOR GALVEZ",
      "GARIBALDI",
      "LANDETA",
      "LAS ROSAS",
      "SARGENTO CABRAL",
      "SAN BERNARDO",
      "GUADALUPE NORTE",
      "SAN JOSE DE LA ESQUINA",
      "PROGRESO",
      "COLONIA MARGARITA",
      "SAN EUGENIO",
      "NUEVO TORINO",
      "CEPEDA",
      "ARROYO LEYES",
      "SANCTI SPIRITU",
      "SAN JUSTO",
      "SAN CRISTOBAL",
      "FLORENCIA",
      "LAS TUNAS",
      "CAPITAN BERMUDEZ",
      "CORONEL ARNOLD",
      "CHAÑAR LADEADO",
      "PUEBLO ESTHER",
      "SALTO GRANDE",
      "TRAILL",
      "CABAL",
      "CAYASTA",
      "GARABATO",
      "ACEBAL",
      "MELINCUE",
      "JOSEFINA",
      "MAGGIOLO",
      "LA CHISPA",
      "SOLEDAD",
      "HELVECIA",
      "VILLA CONSTITUCION",
      "MONTE OSCURIDAD",
      "SAN LORENZO",
      "COLONIA BIGAND",
      "VIDELA",
      "EMILIA",
      "LAS TOSCAS",
      "GREGORIA PEREZ DE DENIS",
      "ZAVALLA",
      "COLONIA ALDAO",
      "COLONIA ANA",
      "SANFORD",
      "CORONEL DOMINGUEZ",
      "ROLDAN",
      "PLAZA CLUCELLAS",
      "ESTACION CLUCELLAS",
      "SAN EDUARDO",
      "ESTHER",
      "CARMEN DEL SAUCE",
      "LARRECHEA",
      "CASAS",
      "CARCARAÑA",
      "ARROYO CEIBAL",
      "CHAPUY",
      "LOGROÑO",
      "LAS GARZAS",
      "RUEDA",
      "LEHMANN",
      "CAÑADA DEL UCLE",
      "SAUCE VIEJO",
      "BELLA ITALIA",
      "PUEBLO MUÑOZ",
      "CALCHAQUI",
      "SAN JERONIMO NORTE",
      "SANTA ROSA DE CALCHINES",
      "DIEGO DE ALVEAR",
      "FIRMAT",
      "LA CAMILA",
      "CASTELAR",
      "SOLDINI",
      "ALCORTA",
      "OLIVEROS",
      "SAN CARLOS SUD",
      "LAZZARINO",
      "ANGELICA",
      "PUEBLO ANDINO",
      "LOMA ALTA",
      "LA CRIOLLA",
      "MAXIMO PAZ",
      "INTIYACO",
      "BAUER Y SIGEL",
      "CAÑADA DE GOMEZ",
      "SERODINO",
      "CENTENO",
      "MARIA LUISA",
      "CARMEN",
      "LA BRAVA",
      "SAN MARTIN NORTE",
      "ARTEAGA",
      "HUGHES",
      "LA RUBIA",
      "ALBARELLOS",
      "SAN JOSE",
      "CULULU",
      "SAN VICENTE",
      "BIGAND",
      "IRIGOYEN",
      "RUFINO",
      "MACIEL",
      "SARMIENTO",
      "TEODELINA",
      "HUMBOLDT",
      "LOPEZ",
      "SAN JERONIMO SUD",
      "CARLOS PELLEGRINI",
      "FRONTERA",
      "AURELIA",
      "BUSTINZA",
      "VILA",
      "TOSTADO",
      "DESVIO ARIJON",
      "MONTE VERA",
      "FRANCK",
      "EL SOMBRERITO",
      "MOISES VILLE",
    ],
    "SANTIAGO DEL ESTERO": [
      "CHILCA JULIANA",
      "GARZA",
      "PINTO",
      "CAMPO GALLO",
      "DOÑA LUISA",
      "SABAGASTA",
      "SAN RAMON - LA DARSENA",
      "VILLA ZANJON",
      "VILLA MATOQUE",
      "GUAMPACHA",
      "VILLA GUASAYAN",
      "POZO DEL TOBA",
      "QUEBRACHO COTO",
      "VILLA ROBLES",
      "SOL DE MAYO",
      "JUANILLO",
      "PUNTA POZO",
      "EL AIBE",
      "ABRA GRANDE",
      "REMES",
      "SAN BENITO",
      "EL DEAN",
      "SAN VICENTE",
      "SANTA CATALINA",
      "SANTA MARIA",
      "CASPI CORRAL",
      "VACA HUAÑUNA",
      "MELERO",
      "LA NENA - LA SIMONA",
      "TRES CRUCES",
      "YUCHAN",
      "LA NORIA",
      "SAUCE SOLO",
      "AMAMA",
      "VILLA BRANA",
      "LIBERTAD",
      "NEGRA MUERTA",
      "KILOMETRO 49",
      "CAMPO GRANDE",
      "VILLA MERCEDES",
      "SANTO DOMINGO",
      "AMICHA",
      "LESCANO",
      "LOS OVEJEROS",
      "SOTELO",
      "LOS ROMANOS - SANTO DOMINGO",
      "VILLA HIPOLITA",
      "VACA HUMAN",
      "TIO POZO",
      "VILLA NUEVA",
      "HUACHANA",
      "SUMAMAO",
      "AHI VEREMOS",
      "ACOS - POZO DEL ARBOLITO",
      "SAN ANTONIO - ROLDAN",
      "HOYON",
      "EL SAUZAL",
      "ATOJ POZO",
      "VUELTA DE LA BARRANCA",
      "EL CRUCE",
      "LAS TINAJAS",
      "COLONIA EL SIMBOLAR",
      "LA BANDA",
      "FORRES",
      "LOS QUIROGA",
      "POZO HONDO",
      "EL CHARCO",
      "AREA SIN GOBIERNO",
      "LUGONES",
      "TACAÑITAS",
      "VILLA SALAVINA",
      "VILLA FIGUEROA",
      "LORETO",
      "POZO BETBEDER",
      "COLONIA TINCO",
      "TINTINA",
      "LA AURORA",
      "VILLA RIO HONDO",
      "RAMIREZ DE VELAZCO",
      "CHAUPI POZO",
      "REAL SAYANA",
      "SAN PEDRO",
      "EL COLORADO",
      "POZUELOS",
      "MATARA",
      "VILLA SILIPICA",
      "PAMPA DE LOS GUANACOS",
      "SUMAMPA",
      "SAN JOSE DEL BOQUERON",
      "TERMAS DE RIO HONDO",
      "ICAÑO",
      "TOMAS YOUNG",
      "NUEVA FRANCIA",
      "VILMER",
      "LAPRIDA",
      "TAPSO",
      "HERRERA",
      "BANDERA",
      "WEISBURD",
      "COLONIA ALPINA",
      "SAN PEDRO DE GUASAYAN",
      "RAPELLI",
      "VILLA UNION",
      "AÑATUYA",
      "SANTIAGO DEL ESTERO",
      "QUIMILI",
      "FORTIN INCA",
      "CUATRO BOCAS",
      "ANTAJE",
      "PALO NEGRO",
      "CHAUCHILLAS",
      "TABOADA",
      "ARDILES",
      "VILLA ATAMISQUI",
      "SELVA",
      "MEDELLIN",
      "LILO VIEJO - PATAY",
      "LA CAÑADA",
      "MALBRAN",
      "LOS JURIES",
      "DONADEU",
      "NUEVA ESPERANZA",
      "CHOYA",
      "ESTACION SIMBOLAR",
      "EL BOBADAL",
      "LAS DELICIAS",
      "OTUMPA",
      "EL CUADRADO",
      "VILELAS",
      "GRAMILLA",
      "SANTOS LUGARES",
      "FERNANDEZ",
      "ESTACION ROBLES",
      "EL MOJON",
      "AVERIAS",
      "SACHAYOJ",
      "COLONIA SAN JUAN",
      "BREA POZO",
      "CASARES",
      "BELTRAN",
      "EL ARENAL",
      "SOL DE JULIO",
      "COLONIA DORA",
      "CAÑADA ESCOBAR",
      "LAVALLE",
      "LOS NUÑEZ",
      "EL CABURE",
      "VINARA",
      "ESTACION ATAMISQUI",
      "CLODOMIRA",
      "SUNCHO CORRAL",
      "LA INVERNADA",
      "BANDERA BAJADA",
      "FRIAS",
      "MONTE QUEMADO",
      "LOS PIRPINTOS",
      "VILLA OJO DE AGUA",
      "ARGENTINA",
      "VILLA MAILIN",
      "ARRAGA",
      "GUARDIA ESCOLTA",
      "LOS TELARES",
      "VILLA LA PUNTA",
    ],
    "TIERRA DEL FUEGO": [
      "USHUAIA",
      "AREA SIN GOBIERNO",
      "RIO GRANDE",
      "TOLHUIN",
    ],
    "TUCUMÁN": [
      "LOS RALOS",
      "ALPACHIRI Y EL MOLINO",
      "SIMOCA",
      "SOLDADO MALDONADO",
      "LOS PEREYRA",
      "ARCADIA",
      "ACHERAL",
      "TAFI DEL VALLE",
      "EL MOLLAR",
      "SANTA ROSA DE LEALES Y LAGUNA BLAN",
      "SAN PABLO Y VILLA NOUGUES",
      "LA FLORIDA Y LUISIANA",
      "BURRUYACU",
      "MONTE BELLO",
      "ANCAJULI",
      "AGUA DULCE Y LA SOLEDAD",
      "YERBA BUENA",
      "LOS NOGALES",
      "DELFIN GALLO",
      "LOS SOSA",
      "LA COCHA",
      "AREA SIN GOBIERNO",
      "RIO CHICO Y NUEVA TRINIDAD",
      "SANTA ANA",
      "VILLA PADRE MONTI",
      "GASTONA Y BELICHA",
      "SAN ANDRES",
      "SAN JOSE DE LA COCHA",
      "RIO COLORADO",
      "EL BRACHO Y EL CEVILAR",
      "MONTEROS",
      "PIEDRABUENA",
      "ESCABA",
      "SARGENTO MOYA",
      "LAS CEJAS",
      "SAN FELIPE Y SANTA BARBARA",
      "LA TRINIDAD",
      "CEVIL REDONDO",
      "EL NARANJITO",
      "GARMENDIA",
      "EL MANANTIAL",
      "EL CHAÑAR",
      "TAFI VIEJO",
      "TRANCAS",
      "BELLA VISTA",
      "LAS TALITAS",
      "MANUEL GARCIA FERNANDEZ",
      "MEDINA",
      "LOS GOMEZ",
      "ALTO VERDE Y LOS GUCHEA",
      "VILLA QUINTEROS",
      "JUAN BAUTISTA ALBERDI",
      "SANTA LUCIA",
      "SAN JAVIER",
      "EL MOJON",
      "RACO",
      "ATAHONA",
      "COLALAO DEL VALLE",
      "ESTACION ARAOZ Y TACANAS",
      "MANUELA PEDRAZA",
      "TENIENTE BERDINA",
      "EL POLEAR",
      "AMAICHA DEL VALLE",
      "COLOMBRES",
      "EL CERCADO",
      "SANTA CRUZ Y LA TUNA",
      "LA RAMADA Y LA CRUZ",
      "ESQUINA Y MANCOPA",
      "HUASA PAMPA",
      "MONTEAGUDO",
      "EL NARANJO Y EL SUNCHAL",
      "LAS TALAS",
      "7 DE ABRIL",
      "LEALES",
      "CHICLIGASTA",
      "RANCHILLOS Y SAN MIGUEL",
      "LAMADRID",
      "QUILMES Y LOS SUELDOS",
      "EL TIMBO",
      "PAMPA MAYO",
      "LOS PEREZ",
      "CIUDACITA",
      "LA ESPERANZA",
      "EL CADILLAL",
      "SAN ISIDRO DE LULES",
      "LOS PUESTOS",
      "VILLA BELGRANO",
      "SAN MIGUEL DE TUCUMAN",
      "BANDA DEL RIO SALI",
      "AGUILARES",
      "LOS SARMIENTOS Y LA TIPA",
      "LOS BULACIO Y LOS VILLAGRA",
      "RIO SECO",
      "EL SACRIFICIO",
      "TACO RALO",
      "YANIMA",
      "LEON ROUGES Y STA",
      "AMBERES",
      "BUENA VISTA",
      "TAPIA",
      "FAMAILLA",
      "CONCEPCION",
      "BENJAMIN ARAOZ  Y EL TAJAMAR",
      "RUMI PUNCO",
      "EL PUESTITO",
      "SAN PEDRO Y SAN ANTONIO",
      "CAPITAN CACERES",
      "SAN PEDRO DE COLALAO",
      "CHOROMORO",
      "ALDERETES",
      "GRANEROS",
    ],
    // Agrega más provincias y sus municipios
  };
  
 // Elementos select en el DOM
 const selectProvincia = document.getElementById("provincia");
 const selectMunicipio = document.getElementById("municipio");
 
 // Evento al cambiar de provincia
 selectProvincia.addEventListener("change", function () {
   const provinciaSeleccionada = selectProvincia.value;
 
   // Limpiar el select de municipios
   selectMunicipio.innerHTML =
     '<option value="">Seleccione un municipio</option>';
 
   // Si se selecciona una provincia, cargar los municipios correspondientes
   if (provinciaSeleccionada && municipiosPorProvincia[provinciaSeleccionada]) {
     selectMunicipio.disabled = false;
 
     // Rellenar el select de municipios
     municipiosPorProvincia[provinciaSeleccionada].forEach((municipio) => {
       const option = document.createElement("option");
       option.value = municipio;
       option.textContent = municipio;
       selectMunicipio.appendChild(option);
     });
   } else {
     selectMunicipio.disabled = true; // Deshabilitar si no hay provincia seleccionada o si no hay municipios
   }
      
 });
 




//   // Elementos select en el DOM
//   const selectProvincia = document.getElementById("provincia");
//   const selectMunicipio = document.getElementById("municipio");
  
//   // Evento al cambiar de provincia
//   selectProvincia.addEventListener("change", function () {
//     const provinciaSeleccionada = selectProvincia.value;
  
//     // Limpiar el select de municipios
//     selectMunicipio.innerHTML =
//       '<option value="">Seleccione un municipio</option>';
  
//     // Si se selecciona una provincia, cargar los municipios correspondientes
//     if (provinciaSeleccionada && municipiosPorProvincia[provinciaSeleccionada]) {
//       selectMunicipio.disabled = false;
  
//       // Rellenar el select de municipios
//       municipiosPorProvincia[provinciaSeleccionada].forEach((municipio) => {
//         const option = document.createElement("option");
//         option.value = municipio;
//         option.textContent = municipio;
//         selectMunicipio.appendChild(option);
//       });
//     } else {
//       selectMunicipio.disabled = true; // Deshabilitar si no hay provincia seleccionada o si no hay municipios
//     }
//     console.log(selectProvincia.value)
//     console.log(selectMunicipio.value)
    
//   });
  